main/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', views.index, name='index'),
    path('upload_creation/', views.upload_creation, name='upload_creation'),
    path('done_today/', views.done_today, name='done_today'),
    path('auth/', include('django.contrib.auth.urls')), 
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/users/urls.py
from django.contrib.auth import views as auth
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
      'logout/',
      auth.LogoutView.as_view(template_name='users/logged_out.html'),
      name='logout'
    ),
    path(
      'login/',
      auth.LoginView.as_view(template_name='users/login.html'),
      name='login'
    ),
    path(
      'password_change/',
      auth.PasswordChangeView.as_view(template_name='users/password_change_form.html'),
      name='password_change'
    ),
    path(
      'password_change/done/',
      auth.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
      name='password_change_done'
    ),
    path(
      'password_reset/',
      auth.PasswordResetView.as_view(template_name='users/password_reset_form.html'),
      name='password_reset'
    ),
    path(
      'password_reset/done/',
      auth.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
      name='password_reset_done'
    ),
    path(
      'reset/<uidb64>/<token>/',
      auth.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
      name='password_reset_confirm'
    ),
    path(
      'reset/done/',
      auth.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
      name='password_reset_complete'
    ),
] 

main/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="en"> 
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/sketchy.min.css">
    {% block title %}<title>Get Inspiration</title>{% endblock %}
  </head>
  <body>
    <header>
      {% include 'nav.html' %}
    </header>
    <main>
    
      <div class="container py-5">
      {% block content %}
      {% endblock %}
      </div> 
    </main>
    <footer class="border-top text-center py-3">
      <p>© 2021 Copyright Get Inspiration</p> 
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/index.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block content %} 

<br><br><br>
<div><img src="/static/img/Get_Inspiration_logo.png" alt="Get Inspiration logo" style="display: block; margin-left: auto; margin-right: auto;"></div>
<br><br><br><br><br><br>


<div class="row">
   <div class="col-12 col-md-6">
      <div class="accordion" id="accordionExample1">
         <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne1">
               <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne1" aria-expanded="true" aria-controls="collapseOne1">
               Today`s combination
               </button>
            </h2>
            <div id="collapseOne1" class="accordion-collapse collapse show" aria-labelledby="headingOne1" data-bs-parent="#accordionExample1" style>
               <div class="accordion-body">
                  <p class="text-center">Draw or write a short story about</p>
                  <p class="text-center">Character:  {{ combi1.character }}</p>
                  <p class="text-center">Location: {{ combi1.location }}</p>
                  <p class="text-center">Additional detail: {{ combi1.detail }}</p>
               </div>
            </div>
         </div>
         <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo1">
               <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo1" aria-expanded="false" aria-controls="collapseTwo1">
               Extra combination
               </button>
            </h2>
            <div id="collapseTwo1" class="accordion-collapse collapse" aria-labelledby="headingTwo1" data-bs-parent="#accordionExample1" style="">
               <div class="accordion-body">
                  <p class="text-center">Draw or write a short story about</p>
                  <p class="text-center">Character:  {{ combi2.character }}</p>
                  <p class="text-center">Location: {{ combi2.location }}</p>
                  <p class="text-center">Additional detail: {{ combi2.detail }}</p>
               </div>
            </div>
         </div>
      </div><br>
   </div>

   
   <div class="col-12 col-md-6">
      <a href="{% url 'done_today' %}" style="text-decoration: none;">
         <button type="button" class="btn btn-outline-success" style="display: block; margin-left: auto; margin-right: auto;">I've done today's task!</button>
      </a><br>
      <div class="accordion">
         <div class="accordion-item">
            <div class="accordion-body">
            <div class="card-body justify-content-center d-flex align-items-center">
                  <div>
                     <h3 class="text-center text-success">Next task in:</h3>
                     <h3 class="text-center">{{ time_left }}</h3>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>


<br><br><br><br><br><br>
<h3 class="text-center text-success">Your progress for {{ month_and_year }}</h3>
<br>
<table class="table table-hover">
   <thead>
      <tr>
         <th scope="col">Monday</th>
         <th scope="col">Tuesday</th>
         <th scope="col">Wednesday</th>
         <th scope="col">Thursday</th>
         <th scope="col">Friday</th>
         <th scope="col">Saturday</th>
         <th scope="col">Sunday</th>
      </tr>
   </thead>
   <tbody>
      {% for week in month %}
      <tr>
         {% for day in week %}
         <td>{{ day|safe }}</td>
         {% endfor %}
      </tr>
      {% endfor %}
   </tbody>
</table>
<br><br><br><br><br><br>


<h3 class="text-center text-success">Share your creation</h3><br>
<div class="accordion" id="accordionExample2">
   <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne2">
         <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne2" aria-expanded="true" aria-controls="collapseOne2">
         Upload story
         </button>
      </h2>
      <div id="collapseOne2" class="accordion-collapse collapse show" aria-labelledby="headingOne2" data-bs-parent="#accordionExample2" style>
         <div class="accordion-body">
            <form method="post" action="{% url 'upload_creation' %}" >
               {% csrf_token %}
               <div class="form-group">
                  <label for="{{ form.story.id_for_label }}" class="form-label mt-4">Write your story here:</label>
                  <textarea class="form-control"  id="{{ form.story.id_for_label }}" name="{{ form.story.html_name }}" rows="3"></textarea><br> 
                  <button type="submit" class="btn btn-outline-success">
                  Upload
                  </button>
               </div>
            </form>
         </div>
      </div>
   </div>
   <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo2">
         <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo2" aria-expanded="false" aria-controls="collapseTwo2">
         Upload painting / drawing
         </button>
      </h2>
      <div id="collapseTwo2" class="accordion-collapse collapse" aria-labelledby="headingTwo2" data-bs-parent="#accordionExample2" style="">
         <div class="accordion-body">
            <form method="post" enctype="multipart/form-data" action="{% url 'upload_creation' %}" >
               {% csrf_token %}
               <div class="form-group">
                  <label for="{{ form.image.id_for_label }}" class="form-label mt-4">Choose image to upload:</label>
                  {{ form.image|addclass:'form-control' }}<br>
                  <button type="submit" class="btn btn-outline-success">
                  Upload
                  </button>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
<br><br><br><br><br><br>
<script>
   function open_art() {
       var art = document.getElementById('ArtGallery');
       var story = document.getElementById('StoryGallery');
       art.style.display = 'block';
       story.style.display = 'none';
   }
   
   function open_story() {
       var art = document.getElementById('ArtGallery');
       var story = document.getElementById('StoryGallery');    
       art.style.display = 'none';
       story.style.display = 'block';
   }
</script>


<h3 class="text-center text-success">Don't know what to draw or write? Get inspired by works of other people:</h3><br>
<div class="row">
   <div class="col-6"><button onclick="open_art()" class="btn btn-outline-success" style="display: block; margin-left: auto; margin-right: auto;">Art gallery</button></div>
   <div class="col-6"><button onclick="open_story()" class="btn btn-outline-success" style="display: block; margin-left: auto; margin-right: auto;">Story gallery</button></div>
</div>
<br>
<div id="ArtGallery">
   <div class="row">
      {% for upload in uploads %}
      {% if upload.image %}
      <div class="col-12 col-md-4">
         {% thumbnail upload.image "270x270" crop="center" upscale=True as im %}
         <p>
         <p><img class="card-img" src="{{ im.url }}"></p>
         </p>
         {% endthumbnail %}
      </div>
      {% endif %}
      {% endfor %}
   </div>
</div>
<div id="StoryGallery" style="display: none;">
   {% for upload in uploads %}
   {% if upload.story %}
   <figure>
      <blockquote>
         <p>{{ upload.story|truncatechars:900 }}</p>
      </blockquote>
      <figcaption class="blockquote-footer">
         {{ upload.author.username }}
      </figcaption>
   </figure>
   {% endif %}
   {% endfor %}
</div>
<br><br><br><br><br><br>
<h3 class="text-center text-success">About the Get Inspiration project</h3><br>
<p class="text-center">
Get inspiration is the website that helps creators with practicing their skills on a daily basis. 
</p><p class="text-center">
How does it works? Pretty simple.  When someone doesn't know what to draw, one may open our website Get inspiration. Website will show today`s random combination of words - one character, one location and one additional detail. This combination of words will be the basis for the future creation. Next, you may create a drawing, a small story or some other work of art. The main requirement: each object from todays random combination should be included into the creation.
</p><p class="text-center">
Since one particular combination may not suit you, every day our website generates two combinations so that you can choose between the two.
</p><p class="text-center">
What is more, Get Inspiration provides you an opportunity to register and mark your daily progress in a personal calendar. Your daily progress is the fact that you have completed today`s challenge. As you see how many days in a row you have completed this day's, you`ll stay motivated not to miss a single day of practicing and improving skills!
</p>
{% endblock %}

main/templates/nav.html
{% load thumbnail %}
<nav>
    <div class="row">
        <div class="col-4"></div>

        <div class="col-4 justify-content-center d-flex align-items-center">
            {% thumbnail "/static/img/your_place.png" "400x400" crop="center" upscale=True as im %}
                <a href="{% url 'index' %}"><img class="card-img" src="/static/img/your_place.png" alt="your place for inspiration"></a>
            {% endthumbnail %}
        </div>

        <div class="col-4 justify-content-center d-flex align-items-center">
            {% if user.is_authenticated %}                
                    <a class="nav-link" href="{% url 'users:logout' %}">Log Out</a>  
            {% else %}
                <a class="nav-link" href="{% url 'users:signup' %}"><span >Sign Up</span></a>
                <a class="nav-link" href="{% url 'users:login' %}">Sign In</a>
            {% endif %}
        </div>              
    </div>
<nav>